users:
  cc_user:
    password: cc_user
    portals:
      - ClearCATS:
        - User
  cc_admin:
    password: cc_admin
    portals:
      - ClearCATS:
        - Admin
  faculty:
    password: faculty
    portals:
      - ClearCATS:
  cecd_user:
    password: cecd_user
    portals:
      - ClearCATS:
        - Admin: [5002]
  wakibbe:
    password: wakibbe
  pgreenld:
    password: pgreenld
